# Generated by Django 3.2.9 on 2022-10-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_upload_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(max_length=128, upload_to='files', verbose_name='文件'),
        ),
    ]
