# Generated by Django 3.2.9 on 2022-10-16 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_mccabe'),
    ]

    operations = [
        migrations.AddField(
            model_name='mccabe',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.upload', verbose_name='文件'),
        ),
        migrations.AddField(
            model_name='upload',
            name='nid',
            field=models.CharField(max_length=32, null=True, verbose_name='文件id'),
        ),
    ]
