# Generated by Django 3.2.9 on 2022-10-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20221016_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mccabe',
            name='file',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='nid',
        ),
        migrations.AddField(
            model_name='mccabe',
            name='path',
            field=models.FilePathField(null=True, verbose_name='路径'),
        ),
    ]
