# Generated by Django 3.2.9 on 2022-10-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20221016_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='nid',
            field=models.CharField(default=0, max_length=64, verbose_name='nid'),
        ),
    ]
